# NLA lake versus reservoir
# Code generated by Jessica Corman; updates by Bridget Deemer

# If other data is desired, see "EPA data download.R" file

# Read necessary dataframes into R
lake <- read.csv("Data/NLA2007_lakes.csv") # Sampled lake info
chem <- read.csv("Data/NLA2007_chem.csv") # Chemical Condition Estimates
temp <- read.csv("Data/NLA2007_temp.csv") # Profile data
basin <- read.csv("Data/NLA2007_basin.csv") #Basin data
temp5 <- subset(temp, DEPTH == 5)
secchi <- read.csv("Data/NLA2007_secchi.csv") #secchi data

# Merge all data; there is probably a cleaner way to do this
# Going to use the dplyr package since it is what I am familiar with, but we should chat about what type of "merge" is appropriate
#cdata <- merge(lake, chem, by="SITE_ID")
#ddata <- merge(cdata, temp5, by="SITE_ID")

#Trying out dplyr package for this
#Full join retains all the values in all the rows and just fills in "NA" when data is missing for that Site ID
#So... it is inflating the number of observations rather than collapsing them like the merge function did
library(dplyr)
cdata<-full_join(lake,chem, by="SITE_ID")
ddata<-full_join(cdata,temp5,by="SITE_ID")
sdata<- full_join(ddata,secchi,by="SITE_ID")
bdata <- full_join(sdata, basin, by="SITE_ID")
#Then there are some duplicated column names that need to be eliminated
bdata <- bdata[!duplicated(names(bdata))]

#I think we want to filter out the reference lakes since these weren't randomly sampled
#SITE_TYPE lets us filter out the lakes that weren't part of the "probablility" sample.  
#This is a little different than the RT_NLA column that Jess used for the LA_Temp plot
edata<-bdata %>%
  filter(SITE_TYPE.y=="PROB_Lake")

#Now create subsets of data for Region 8 and Region 10 analysis
Region8<-edata %>%
  filter(EPA_REG.x=="Region_8")
Region10<-edata %>%
  filter(EPA_REG.x=="Region_10")


library(ggplot2)

temp5.plot <- ggplot(edata, aes(x=EPA_REG.x, y=TEMP_FIELD)) +
  geom_point(size=3, alpha=0.5, aes(color=LAKE_ORIGIN.x, shape=RT_NLA.x), 
             position=position_dodge(0.5)) +
  theme_classic(12) +
  theme(axis.text.x = element_text(angle=90)) +
  ylab("Temperature @ 5 m")

ggsave("Figures/Temp_at_5m.pdf", temp5.plot)

LA_temp.plot <- ggplot(edata, aes(x=log(LAKEAREA), y=TEMP_FIELD)) +
  geom_point(size=3, alpha=0.5, aes(color=LAKE_ORIGIN.x, shape=RT_NLA.x), 
             position=position_dodge(0.5)) +
  theme_classic(12) +
  ylab("Temperature @ 5 m") +
  xlab("LN(Lake Area)") +
  stat_smooth(data=subset(edata, LAKE_ORIGIN.x == "MAN-MADE"), 
              color="red", method="lm") +
  stat_smooth(data=subset(edata, LAKE_ORIGIN.x == "NATURAL"), 
              color="blue", method="lm")

ggsave("Figures/LA_temp.pdf", LA_temp.plot)

#Boxplot functions to help with formatting:

#To get nice log scale axis labels we make a base_breaks function
base_breaks <- function(n = 10){
  function(x) {
    axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
  }
}

#To combine multiple plots into one output file
multiplot<- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

#Surface Area Comparisons
sarea.plot<-edata %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=LAKEAREA))+
  geom_boxplot()+
    coord_trans(y="log10")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Whole Dataset")+
  ylab(expression('Surface Area (km'^-2*')'))

ggsave("Figures/Surface_Area_Whole_Dataset.pdf", sarea.plot)

sarea_reg_8.plot<-Region8 %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=LAKEAREA))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Region 8")+
  ylab(expression('Surface Area (km'^-2*')'))

ggsave("Figures/Surface_Region_8.pdf", sarea_reg_8.plot)

sarea_reg_10.plot<-Region10 %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=LAKEAREA))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Region 10")+
  ylab(expression('Surface Area (km'^-2*')'))

ggsave("Figures/Surface_Region_10.pdf", sarea_reg_10.plot)

multiplot(sarea.plot,sarea_reg_10.plot,sarea_reg_8.plot,cols=1)

#Perimeter Comparisons
perim.plot<-edata %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=LAKEPERIM))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Whole Dataset")+
  ylab("Perimeter (km)")

ggsave("Figures/Perimeter_Whole_Dataset.pdf", perim.plot)

perim_reg_8.plot<-Region8 %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=LAKEPERIM))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Region 8")+
  ylab("Perimeter (km)")

ggsave("Figures/Perimeter_Region_8.pdf", perim_reg_8.plot)

perim_reg_10.plot<-Region10 %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=LAKEPERIM))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Region 10")+
  ylab("Perimeter (km)")

ggsave("Figures/Perimeter_Region_10.pdf", perim_reg_10.plot)

multiplot(perim.plot,perim_reg_8.plot,perim_reg_10.plot,cols=1)

#Secchi Comparisons

secchi.plot<-edata %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=SECMEAN))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Whole Dataset")+
  ylab("Mean Secchi Depth (m)")

ggsave("Figures/Secchi_Whole_Dataset.pdf", secchi.plot)

secchi_reg_8.plot<-Region8 %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=SECMEAN))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Region 8")+
  ylab("Mean Secchi Depth (m)")

ggsave("Figures/Secchi_Region_8.pdf", secchi_reg_8.plot)

secchi_reg_10.plot<-Region10 %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=SECMEAN))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Region 10")+
  ylab("Mean Secchi Depth (m)")

ggsave("Figures/Secchi_Region_10.pdf", secchi_reg_10.plot)

multiplot(secchi.plot,secchi_reg_8.plot,secchi_reg_10.plot)

#Catchment Area: Lake Area

cala.plot<- edata %>%
  mutate(catchlake = BASINAREA_KM2 / LAKEAREA) %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=catchlake))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("All Data")+
  ylab("Catchment Area:Lake Area")

ggsave("Figures/CALA.pdf", cala.plot)

cala_reg_8.plot<- Region8 %>%
  mutate(catchlake = BASINAREA_KM2 / LAKEAREA) %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=catchlake))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Region 8")+
  ylab("Catchment Area:Lake Area")

ggsave("Figures/CALA_Region_8.pdf", cala_reg_8.plot)

cala_reg_10.plot<- Region10 %>%
  mutate(catchlake = BASINAREA_KM2 / LAKEAREA) %>%
  ggplot(aes(x=LAKE_ORIGIN.y,y=catchlake))+
  geom_boxplot()+
  coord_trans(y="log10")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  scale_y_continuous(breaks=base_breaks())+
  coord_trans(y="log10")+
  xlab("Region 10")+
  ylab("Catchment Area:Lake Area")

ggsave("Figures/CALA_Region_10.pdf", cala_reg_10.plot)

multiplot(cala.plot,cala_reg_8.plot,cala_reg_10.plot,cols=1)

#### Scatterplot of Secchi Disk vs Catchment Area:Lake Area ###########

secc_cala.plot<-edata %>%
  mutate(catchlake = BASINAREA_KM2 / LAKEAREA) %>%
  mutate(lncatlak = log(catchlake)) %>%
  mutate(lnsecmean = log(SECMEAN)) %>%
  ggplot(aes(x=lncatlak,y=lnsecmean,colour=LAKE_ORIGIN.x))+
  geom_point()+
  xlab("Ln Catchment Area:Lake Area")+
  ylab("Ln Secchi Depth (m)")+
  geom_smooth(method="lm")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  theme(legend.title=element_blank())

ggsave("Figures/CALA_v_Secc.pdf", secc_cala.plot)

secc_cala_reg_8.plot<-Region8 %>%
  mutate(catchlake = BASINAREA_KM2 / LAKEAREA) %>%
  mutate(lncatlak = log(catchlake)) %>%
  mutate(lnsecmean = log(SECMEAN)) %>%
  ggplot(aes(x=lncatlak,y=lnsecmean,colour=LAKE_ORIGIN.x))+
  geom_point()+
  xlab("Ln Catchment Area:Lake Area")+
  ylab("Ln Secchi Depth (m)")+
  geom_smooth(method="lm")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  theme(legend.title=element_blank())

ggsave("Figures/CALA_v_Secc_Reg_8.pdf", secc_cala_reg_8.plot)

secc_cala_reg_10.plot<-Region10 %>%
  mutate(catchlake = BASINAREA_KM2 / LAKEAREA) %>%
  mutate(lncatlak = log(catchlake)) %>%
  mutate(lnsecmean = log(SECMEAN)) %>%
  ggplot(aes(x=lncatlak,y=lnsecmean,colour=LAKE_ORIGIN.x))+
  geom_point()+
  xlab("Ln Catchment Area:Lake Area")+
  ylab("Ln Secchi Depth (m)")+
  geom_smooth(method="lm")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),axis.line=element_line(colour="black"))+
  theme(legend.title=element_blank())

ggsave("Figures/CALA_v_Secc_Reg_10.pdf", secc_cala_reg_10.plot)

multiplot(secc_cala.plot,secc_cala_reg_8.plot,secc_cala_reg_10.plot,cols=1)

#Statistics on Full Linear Regression
#Regression is significant but R2 is only 0.03 :p
attach(edata)
catchlake<-log(BASINAREA_KM2 / LAKEAREA)
secmean<-log(SECMEAN)
fit<-lm(catchlake~secmean)
summary(fit)

#Region 8 has very poor R2
#Region 10 has a better one (0.19)
attach(Region10)
catchlake<-log(BASINAREA_KM2 / LAKEAREA)
secmean<-log(SECMEAN)
fit<-lm(catchlake~secmean)
summary(fit)


