# NLA lake versus reservoir
# Code generated by Jessica Corman; updates by xxxx

# If other data is desired, see "EPA data download.R" file

# Read necessary dataframes into R
lake <- read.csv("Data/NLA2007_lakes.csv") # Sampled lake info
chem <- read.csv("Data/NLA2007_chem.csv") # Chemical Condition Estimates
temp <- read.csv("Data/NLA2007_temp.csv") # Profile data
temp5 <- subset(temp, DEPTH == 5)

# Merge all data; there is probably a cleaner way to do this
cdata <- merge(lake, chem, by="SITE_ID")
ddata <- merge(cdata, temp5, by="SITE_ID")

library(ggplot2)

temp5.plot <- ggplot(ddata, aes(x=EPA_REG.x, y=TEMP_FIELD)) +
  geom_point(size=3, alpha=0.5, aes(color=LAKE_ORIGIN.x, shape=RT_NLA.x), 
             position=position_dodge(0.5)) +
  theme_classic(12) +
  theme(axis.text.x = element_text(angle=90)) +
  ylab("Temperature @ 5 m")

ggsave("Figures/Temp_at_5m.pdf", temp5.plot)

LA_temp.plot <- ggplot(ddata, aes(x=log(LAKEAREA), y=TEMP_FIELD)) +
  geom_point(size=3, alpha=0.5, aes(color=LAKE_ORIGIN.x, shape=RT_NLA.x), 
             position=position_dodge(0.5)) +
  theme_classic(12) +
  ylab("Temperature @ 5 m") +
  xlab("LN(Lake Area)") +
  stat_smooth(data=subset(ddata, LAKE_ORIGIN.x == "MAN-MADE"), 
              color="red", method="lm") +
  stat_smooth(data=subset(ddata, LAKE_ORIGIN.x == "NATURAL"), 
              color="blue", method="lm")

ggsave("Figures/LA_temp.pdf", LA_temp.plot)
