#### Lake Pairs Analysis ####
# code generated by jrc     #
# data generated by ks      #
#############################

lp <- read.csv("Data/NLA_lakepairs_50km.csv")
names(lp)
# Columns 1 - 63 include reservoir info
# Columns 64 - 138 include lake info

# Add identifier for pairs
lp$pairs <- seq(1:66)

# Reservoirs of interest
res <- cbind(lp$pairs, as.character(lp$ManMadeSITE_ID))
res <- as.data.frame(res)
# list of res names
res.names <- unique(res[,2])

# Lakes of interest
lakes <- cbind(lp$pairs, as.character(lp$SITE_ID))
lakes <- as.data.frame(lakes)
# list of lake names
lakes.names <- unique(lakes[,2])

pairs <- rbind(res, lakes)
colnames(pairs) <- c("PAIR_ID", "SITE_ID")

# What is different between man-made and natural lakes using pairs within
# 50 km?

# Part 1. secchi disk depth
secchi <- read.csv("Data/NLA2007_secchi.csv") #secchi data

res.secchi <- subset(secchi, SITE_ID %in% res.names)
lakes.secchi <- subset(secchi, SITE_ID %in% lakes.names)


# temperature (more difficult to interpret, tho)

# Catchment area : lake area- boxplots done BD

# scatter plot of secchi disk by catchment area : lake area 
# with distintion between man-made and natural lake- done BD